[package]
name = "libflexguard"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[lib]
name = "flexguard"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.65"
libbpf-rs = "=0.26.0-beta.1"
log = "0.4.17"
scx_utils = { version = "1.0.22", features = ["autopower"] }
simplelog = "0.12"
libc = "0.2.177"

[build-dependencies]
scx_cargo = { version = "1.0.22" }
